apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/config.hash: 6502dddc08d519eb6bbacb5131ad90d0
    kubernetes.io/config.mirror: 6502dddc08d519eb6bbacb5131ad90d0
    kubernetes.io/config.seen: 2018-03-05T00:07:16.263210918-06:00
    kubernetes.io/config.source: file
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: 2018-03-05T06:08:45Z
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler-kube-master-01
  namespace: kube-system
  resourceVersion: "395"
  selfLink: /api/v1/namespaces/kube-system/pods/kube-scheduler-kube-master-01
  uid: a9784f9e-203b-11e8-a8e9-52540005e84e
spec:
  containers:
  - command:
    - kube-scheduler
    - --address=127.0.0.1
    - --leader-elect=true
    - --kubeconfig=/etc/kubernetes/scheduler.conf
    image: gcr.io/google_containers/kube-scheduler-amd64:v1.9.3
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10251
        scheme: HTTP
      initialDelaySeconds: 15
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 15
    name: kube-scheduler
    resources:
      requests:
        cpu: 100m
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/kubernetes/scheduler.conf
      name: kubeconfig
      readOnly: true
  dnsPolicy: ClusterFirst
  hostNetwork: true
  nodeName: kube-master-01
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    operator: Exists
  volumes:
  - hostPath:
      path: /etc/kubernetes/scheduler.conf
      type: FileOrCreate
    name: kubeconfig
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-03-05T06:07:21Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2018-03-05T06:07:23Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2018-03-05T06:07:21Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://b0d82e002afa962b6c9d52ea57fa54ac5c56d695c4a67b7db6752a3296648971
    image: gcr.io/google_containers/kube-scheduler-amd64:v1.9.3
    imageID: docker-pullable://gcr.io/google_containers/kube-scheduler-amd64@sha256:2c17e637c8e4f9202300bd5fc26bc98a7099f49559ca0a8921cf692ffd4a1675
    lastState: {}
    name: kube-scheduler
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2018-03-05T06:07:22Z
  hostIP: 10.128.112.146
  phase: Running
  podIP: 10.128.112.146
  qosClass: Burstable
  startTime: 2018-03-05T06:07:21Z
